Repository atlp-rwanda/champs-ec-fe, pull requests merged in 2024-06, with the labels that each got.

#15 ch(deployment): add deployment with git action #187300181
  .github/workflows/preview.yaml
  .github/workflows/production.yaml
  README.md
  package-lock.json
Labels: ready

#14 Adding Tests for Login
  package-lock.json
  package.json
  src/__tests__/login.test.tsx
  src/app/auth/login/page.tsx
  src/app/auth/signup/page.tsx
  src/hooks/useLogin.ts
  src/validations/LoginValidation.tsx
Labels: ready

#16 ##187504942: Test for signup page
  next.config.mjs
  package-lock.json
  package.json
  src/__tests__/app.test.tsx
  src/__tests__/login.test.tsx
  src/app/auth/login/page.tsx
  src/app/auth/signup/page.tsx
  src/app/page.tsx
  src/components/PopUpModels.tsx
  src/hooks/useLogin.ts
  src/hooks/useSignup.ts
  src/redux/slices/signupReducer .ts
  src/redux/store.ts
Labels: bug, ready

#22 #187300194 two factor authentication for seller
  .env
  package-lock.json
  package.json
  public/otp_removebg.png
  src/__tests__/2FA_Authentication.test.tsx
  src/__tests__/app.test.tsx
  src/__tests__/login.test.tsx
  src/__tests__/seller_dasboard.test.tsx
  src/app/auth/login/page.tsx
  src/app/auth/signup/page.tsx
  src/app/globals.css
  src/app/sellers/page.tsx
  src/components/2faVerification.tsx
  src/components/PopUpModels.tsx
  src/hooks/useLogin.ts
  src/redux/slices/2faAuthenticationSlice.ts
  src/redux/slices/signupReducer .ts
  src/redux/store.ts
  src/validations/otpValidations.tsx
Labels: enhancement, ready

#19 #187300191 Google login integration
  .gitignore
  package-lock.json
  package.json
  src/__tests__/googleauth.test.tsx
  src/app/auth/google/page.tsx
  src/app/auth/login/page.tsx
  src/app/auth/signup/page.tsx
  src/app/page.tsx
  src/components/GoogleButton.tsx
  src/utils/axios.ts
  src/utils/requests.ts
Labels: enhancement, ready

#24 bug fix for two factor authentication…
  .env
  src/redux/slices/2faAuthenticationSlice.ts
Labels: bug, ready

#18 #187300201 Assigning Roles
  .babelrc
  package-lock.json
  package.json
  public/control.png
  public/empty.avif
  public/logo.png
  public/unknown.jpg
  src/__tests__/adminDashboard.test.tsx
  src/app/admin/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/providers.tsx
  src/components/AssigningRoles.tsx
  src/components/Button.tsx
  src/components/Buttonbook.tsx
  src/components/DashboardHeader.tsx
  src/components/UsersAdmin.tsx
  src/hooks/useAdminDashboard.ts
  src/redux/slices/UpdatePasswordSlice.ts
  src/redux/store.ts
  tailwind.config.ts
Labels: ready

#23 #187300193 Users should be presented with reset password link
  package-lock.json
  package.json
  src/__tests__/forgotPassword.test.tsx
  src/__tests__/reset.test.tsx
  src/app/auth/forgotpassword/page.tsx
  src/app/auth/login/page.tsx
  src/app/auth/reset-password/page.tsx
  src/hooks/recover.ts
  src/hooks/reset.ts
  src/validations/RecoverValidation.tsx
  src/validations/ResetValidation.tsx
Labels: ready

#21 Ft seller should be able to create a product-#187300180
  .hintrc
  package-lock.json
  package.json
  public/close.png
  public/save.png
  src/__tests__/2FA_Authentication.test.tsx
  src/__tests__/ClientProvider.test.tsx
  src/__tests__/addproduct.test.tsx
  src/__tests__/layout.test.tsx
  src/app/clientProvider.tsx
  src/app/seller/dashboard/products/page.tsx
  src/components/2faVerification.tsx
  src/components/AddProducts.tsx
  src/components/Sidebar.tsx
  src/helpers/toast.tsx
  src/redux/slices/authSlice.ts
  src/redux/slices/productSlice.ts
  src/redux/store.ts
  src/validations/productValidation.tsx
Labels: ready

#26 Ft disable users #187300202
  .babelrc
  package-lock.json
  package.json
  src/__tests__/deActivateUsers.test.tsx
  src/app/auth/login/page.tsx
  src/app/auth/signup/page.tsx
  src/app/globals.css
  src/components/AssigningRoles.tsx
  src/components/Button.tsx
  src/components/DashboardHeader.tsx
  src/components/DeactivateUser.tsx
  src/components/InputBox.tsx
  src/components/PopUpModels.tsx
  src/components/UsersAdmin.tsx
  src/hooks/useSignup.ts
  src/utils/ReactQueryProvider.tsx
Labels: ready

#25 #187765783: the landing page for the E-champs
  package-lock.json
  package.json
  public/Adsimage.png
  public/Grouped.png
  public/Insta.png
  public/Search.svg
  public/X.png
  public/desk.png
  public/fb.png
  public/force.png
  public/headset.png
  public/image2.png
  public/image3.png
  public/image4.png
  public/logofull.png
  src/__tests__/app.test.tsx
  src/__tests__/page.test.tsx
  src/__tests__/reset.test.tsx
  src/app/auth/login/page.tsx
  src/app/globals.css
  src/app/page.tsx
  src/components/Card.tsx
  src/components/ContDown.tsx
  src/components/Footer.tsx
  src/components/GoogleButton.tsx
  src/components/Header.tsx
  src/components/HeroSection.tsx
  src/components/HomeAds.tsx
  src/components/LatestCard.tsx
  src/components/LatestSection.tsx
  src/components/PopUpModel.tsx
  src/components/ProductList.tsx
  src/components/allProducts.tsx
  src/hooks/reset.ts
  src/hooks/useLogin.ts
  src/types/Product.ts
  src/utils/axios.ts
  tailwind.config.ts
  testconfig.js
Labels: enhancement, ready

#36 Axios Interceptor
  package-lock.json
  src/__tests__/login.test.tsx
  src/__tests__/productView.test.tsx
  src/components/UsersAdmin.tsx
  src/hooks/useLogin.ts
  src/hooks/useSignup.ts
  src/utils/axios.ts
Labels: enhancement, ready

#28 Ft-add-reviews#187300216
  package-lock.json
  package.json
  src/__tests__/averageReview.test.ts
  src/__tests__/ordersOverlayHook.test.tsx
  src/__tests__/productValidation.test.tsx
  src/__tests__/requests.test.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/products/[id]/page.tsx
  src/app/products/page.tsx
  src/app/sellers/products_/[id]/page.tsx
  src/components/AdminViewProduct.tsx
  src/components/Button.tsx
  src/components/BuyerOrdersList.tsx
  src/components/Card.tsx
  src/components/Header.tsx
  src/components/OrdersContainer.tsx
  src/components/ProductList.tsx
  src/components/ReviewCard.tsx
  src/components/ReviewProductPopup.tsx
  src/components/UsersAdmin.tsx
  src/hooks/ordersOverlay.tsx
  src/redux/slices/productSlice.ts
  src/types/Product.ts
  src/utils/averageReviews.ts
  src/utils/axios.ts
  src/utils/requests.ts
Labels: enhancement, ready

#27 #187300210 cart management
  package-lock.json
  package.json
  public/cartAllow.png
  public/delete.png
  public/logo.svg
  public/lowerArrow.png
  public/shoes.png
  public/upperArrow.png
  src/__tests__/2FA_Authentication.test.tsx
  src/__tests__/BuyerProduct.test.tsx
  src/__tests__/Signup.test.tsx
  src/__tests__/ZcartManagement.test.tsx
  src/__tests__/layout.test.tsx
  src/__tests__/toast.test.tsx
  src/app/auth/login/page.tsx
  src/app/clientProvider.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/products/[id]/page.tsx
  src/components/Card.tsx
  src/components/CartContainer.tsx
  src/components/Header.tsx
  src/components/ProductList.tsx
  src/components/Side.tsx
  src/components/Slides.tsx
  src/components/Table.tsx
  src/components/UsableSideOvelay.tsx
  src/components/allProducts.tsx
  src/helpers/toast.tsx
  src/hooks/useLogin.ts
  src/hooks/userCart.tsx
  src/redux/slices/2faAuthenticationSlice.ts
  src/redux/slices/userCartSlice.ts
  src/redux/store.ts
Labels: enhancement, ready

#40 fixing the navbar and it responsiveness
  src/app/page.tsx
  src/app/products/[id]/page.tsx
  src/components/2faVerification.tsx
  src/components/Card.tsx
  src/components/CartContainer.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/ProductList.tsx
  src/components/UsableSideOvelay.tsx
  src/hooks/useLogin.ts
  src/redux/slices/2faAuthenticationSlice.ts
Labels: bug, ready
