Repository atlp-rwanda/champs-ec-fe, pull requests merged in 2024-07, with the labels that each got.

#48 #187854852 Logout
  src/components/AssigningRoles.tsx
  src/components/Header.tsx
  src/hooks/logout.ts
  src/hooks/userCart.tsx
Labels: enhancement, ready

#37 #187300198: A seller should be able to update and delete a product
  package-lock.json
  public/uploads/125add822d4331ce8b9a0cc1b474f2e3.jpg
  public/uploads/828d8f41ab4e08909b4a23c656987978.jpg
  public/uploads/b33219e244403d1d6e434233cddf4533.jpg
  public/uploads/f6625cdef9872c714ff480a35f63ff58.jpg
  src/__tests__/delete.test.tsx
  src/__tests__/productView.test.tsx
  src/__tests__/reset.test.tsx
  src/__tests__/sellerProduct.test.tsx
  src/__tests__/update.test.tsx
  src/__tests__/updateProduct.test.tsx
  src/app/auth/google/page.tsx
  src/app/products/[id]/page.tsx
  src/app/sellers/page.tsx
  src/app/sellers/products_/[id]/page.tsx
  src/app/sellers/products_/page.tsx
  src/components/AdminViewProduct.tsx
  src/components/Button.tsx
  src/components/InputBox.tsx
  src/components/Product/AddProducts.tsx
  src/components/Product/editProduct.tsx
  src/components/Table.tsx
  src/components/confirmDeletePopup.tsx
  src/components/products.tsx
  src/hooks/reset.ts
  src/hooks/update.ts
  src/hooks/useAdminDashboard.ts
  src/redux/slices/2faAuthenticationSlice.ts
  src/redux/slices/UpdateProductSlice.ts
  src/redux/store.ts
  src/validations/productValidation.tsx
Labels: ready

#49 #187300219: buyer track order status
  package-lock.json
  package.json
  public/Vector.png
  public/pngwing.png
  src/__tests__/sellerOrders.test.tsx
  src/app/sellers/orders/page.tsx
  src/components/BuyerOrdersList.tsx
  src/components/CartContainer.tsx
  src/components/Header.tsx
  src/components/SellerOrderDetail.tsx
  src/components/TruckOrder.tsx
  src/components/sellerOrder.tsx
  src/hooks/userCart.tsx
Labels: enhancement, ready

#45 ft(profiles) #187300200 Users should be able to view and edit their profiles
  jest.config.ts
  package-lock.json
  package.json
  src/__tests__/profile.test.tsx
  src/app/(profile)/profile-edit/page.tsx
  src/app/(profile)/profile/page.tsx
  src/components/Header.tsx
  src/components/InputBox.tsx
  src/components/profile/About.tsx
  src/components/profile/ActiveUsers.tsx
  src/components/profile/Order.tsx
  src/components/profile/ProfileHeader.tsx
  src/components/profile/wishlist.tsx
  src/redux/slices/profileSlice.ts
  src/redux/store.ts
  src/validations/userProfileSchema.ts
Labels: ready

#42 #187300222 App notifications
  jest.config.ts
  jest.setup.js
  package-lock.json
  package.json
  src/__tests__/app.test.tsx
  src/__tests__/notifications.test.tsx
  src/__tests__/ordersOverlayHook.test.tsx
  src/__tests__/productSlice.test.tsx
  src/__tests__/requests.test.tsx
  src/__tests__/sellerProduct.test.tsx
  src/components/Header.tsx
  src/components/ui-components/Notification.tsx
  src/components/ui-components/NotificationIcon.tsx
  src/components/ui-components/PingCounter.tsx
  src/redux/slices/notificationSlice.ts
  src/redux/store.ts
  src/types/notification.ts
  src/utils/requests.ts
  src/utils/socket.ts
  testconfig.js
Labels: enhancement, ready

#52 fix(profiles) #187300200 Users should be able to view and edit his /her profile
  .circleci/config.yml
  .hintrc
  jest.config.ts
  package-lock.json
  package.json
  src/app/(profile)/profile-edit/page.tsx
  src/app/(profile)/profile/page.tsx
  src/components/profile/About.tsx
  src/components/profile/Order.tsx
  src/components/profile/wishlist.tsx
  src/redux/slices/2faAuthenticationSlice.ts
  src/redux/slices/profileSlice.ts
  src/redux/slices/userCartSlice.ts
Labels: ready

#51 #187300215:A buyer should be able to make a payment using Stripe API
  package-lock.json
  src/__tests__/payment.test.tsx
  src/__tests__/paymentsSuccess.test.tsx
  src/app/payments/success/page.tsx
  src/app/products/[id]/page.tsx
  src/app/sellers/products_/[id]/page.tsx
  src/components/CartContainer.tsx
  src/components/TruckOrder.tsx
  src/hooks/payment.ts
Labels: ready

#59 #187854958: FE server should run in the docker
  Dockerfile
  docker-compose.yml
  dockerignore
  package-lock.json
Labels: ready

#61 fix(chatbot ui):fixed ui for the chat
  src/__tests__/formatTime.test.tsx
  src/app/globals.css
  src/app/page.tsx
  src/components/ChatConversation.tsx
  src/components/ChatRoomsList.tsx
  src/components/DashboardHeader.tsx
  src/components/LayoutDashboard.tsx
  src/components/Product/AddProducts.tsx
  src/components/chatWrapper.tsx
  src/components/isLogged.tsx
  src/utils/formatTime.tsx
  tailwind.config.ts
Labels: ready

#64 bug-fix: Correct the navbar and dashboard
  src/app/dashboard/users/page.tsx
  src/app/products/[id]/page.tsx
  src/components/Header.tsx
  src/components/LatestCard.tsx
  src/components/UsersAdmin.tsx
  src/components/chartssection.tsx
  src/components/products.tsx
  src/components/profile/About.tsx
  src/components/profile/Order.tsx
  src/components/profile/ProfileHeader.tsx
  src/components/profile/wishlist.tsx
Labels: bug, ready

#62 Bg fix search #187300218 A buyer should be able to search for products
  package-lock.json
  public/product-default.png
  src/__tests__/landingpage.test.tsx
  src/__tests__/productList.test.tsx
  src/__tests__/reset.test.tsx
  src/__tests__/userCart.test.tsx
  src/app/products/[id]/page.tsx
  src/app/products/page.tsx
  src/components/Card.tsx
  src/components/ProductList.tsx
  src/components/Side.tsx
  src/components/Skeleton.tsx
  src/components/allProducts.tsx
  src/types/Product.ts
Labels: ready

#47 #187300213-Buyer should be able to add products to wishlist
  package-lock.json
  package.json
  src/__tests__/productList.test.tsx
  src/__tests__/reviewPopupHook.test.tsx
  src/__tests__/wiishlistOverlayHook.test.tsx
  src/__tests__/wishlistSlice.test.tsx
  src/app/products/[id]/page.tsx
  src/components/Button.tsx
  src/components/BuyerOrdersList.tsx
  src/components/BuyerWishlist.tsx
  src/components/Card.tsx
  src/components/DeleteWishlistPopup.tsx
  src/components/Header.tsx
  src/components/OrdersContainer.tsx
  src/components/ReviewCard.tsx
  src/components/ReviewProductPopup.tsx
  src/components/ReviewsWrapper.tsx
  src/components/productWrapper.tsx
  src/components/wishlistContainer.tsx
  src/hooks/reviewPopup.tsx
  src/hooks/wishlistOverlay.tsx
  src/redux/slices/wishlistSlice.ts
  src/redux/store.ts
Labels: ready

#60 ft(seller stats) seller should see statics on daily basis-#187300236
  package-lock.json
  src/app/dashboard/page.tsx
  src/components/SellerSummary.tsx
Labels: ready

#63 fix(reset password & payments):fixing reset & payment ui
  package-lock.json
  src/__tests__/forgotPassword.test.tsx
  src/__tests__/payment.test.tsx
  src/__tests__/paymentsSuccess.test.tsx
  src/__tests__/reset.test.tsx
  src/app/auth/forgotpassword/page.tsx
  src/app/auth/reset-password/page.tsx
  src/app/payments/success/page.tsx
  src/app/products/[id]/page.tsx
  src/components/Product/editProduct.tsx
  src/hooks/payment.ts
  src/hooks/recover.ts
  src/hooks/update.ts
Labels: ready

#67 Fix(product view): fixing the single product view
  src/components/Header.tsx
  src/components/ReviewsWrapper.tsx
  src/components/Table.tsx
  src/components/singleproduct.tsx
  src/redux/slices/wishlistSlice.ts
Labels: ready

#72 bugFix(allPage): Fix all remain bug into champs Bay
  src/app/(profile)/profile-edit/page.tsx
  src/app/(profile)/profile/page.tsx
  src/app/dashboard/profile/page.tsx
  src/app/globals.css
  src/app/products/[id]/page.tsx
  src/components/AssigningRoles.tsx
  src/components/BuyerWishlist.tsx
  src/components/Card.tsx
  src/components/DashNavbar.tsx
  src/components/EditProfile.tsx
  src/components/GoogleButton.tsx
  src/components/LatestCard.tsx
  src/components/Product/editProduct.tsx
  src/components/ReviewCard.tsx
  src/components/Table.tsx
  src/components/chartssection.tsx
  src/components/headerDash.tsx
  src/components/profile/About.tsx
  src/components/profile/ActiveUsers.tsx
  src/components/profile/Order.tsx
  src/components/profile/ProfileHeader.tsx
  src/components/profile/wishlist.tsx
  src/components/singleproduct.tsx
  src/utils/axios.ts
  src/validations/productValidation.tsx
  src/validations/userProfileSchema.ts
Labels: bug, ready
